### PR TITLE
Fixed breakage due to deprecated `.NumMembers' property.

### PR DESCRIPTION
**Pull request by jaytaylor**
Resolves issue #11.

### CODE REVIEW

**Comment by abourget** [comment]
What about removing it also here?

**Comment by abourget** [comment]
It might occur that we change the list of members internally, and we'd need to keep it in sync. Calling len when needed feels fine with me.

**Comment by jaytaylor** [comment]
Alright, I've gone ahead and removed the deprecated property.

**Comment by abourget** [comment]
Thanks!

**Pull request merged**
